name: Front-end delivery

on:
  push:
    branches: [main, master]

env:
  PORT: ${{ secrets.PORT }}
  REACT_APP_BACKEND: ${{ secrets.REACT_APP_BACKEND }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [12.x, 15.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd front-end
          export NODE_OPTIONS=--openssl-legacy-provider
          npm ci
          npm run build --if-present
      - name: Run tests
        run: |
          cd front-end
          npm test
  dockerize:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:front-end"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: bloombar/data-storage-example-app-front-end:latest
